apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-dev
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd2
    targetRevision: 2.13.3
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/nolet7/helm/main/values/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
