apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-prod
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.12.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/nolet7/helm/main/values/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
