apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-tools
  namespace: argocd
spec:
  description: Platform tools including Linkerd service mesh
  sourceRepos:
    - https://github.com/nolet7/linkerd-test.git
    - https://github.com/nolet7/helm.git
  destinations:
    - namespace: linkerd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
