apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-tools
  namespace: argocd
spec:
  description: "Linkerd Deployment via Argo CD"
  sourceRepos:
    - https://helm.linkerd.io/stable
    - https://github.com/nolet7/helm.git
  destinations:
    - namespace: linkerd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
